### ISSUE TITLE
filtering process

### ISSUE THREAD

**Issue by lytum** [alexa/commonsense-dialogues#1]
thanks for your excellent work.
May I ask, could you also share your filtering code, which is introduced in the section 3.1? or also sharing the filtered data from the existing dataset?
Thanks a lot!

**Comment by g-karthik** [comment]
@lytum thanks for your interest in the work and apologies for the delayed response! Unfortunately, we cannot release the code to filter existing datasets described in section 3.1 or the underlying filtered datasets themselves, but hopefully section 3.1 describes it in sufficient detail for you to implement it yourself!
